source "https://rubygems.org"

ruby "3.4.9"

gem "rails", ">= 8.1.0", "< 8.2"
gem "pg", "~> 1.1"
gem "puma", ">= 6.0"
gem "propshaft"

gem "annes_auth", path: "../../annes_auth"
gem "anne_admin", path: "../../anne_admin"
gem "anne_access", path: "../../anne_access"
gem "anne_loyalty", path: "../../anne_loyalty"
