source "https://rubygems.org"

ruby "3.4.9"

gem "rails", ">= 8.1.0", "< 8.2"
gem "pg", "~> 1.1"
gem "puma", ">= 6.0"
gem "propshaft"
gem "aasm", "~> 5.5.2"

gem "annes_auth", path: "../../annes_auth"
gem "annes_admin", path: "../../annes_admin"
gem "annes_access", path: "../../annes_access"
